import Ionicons from '@expo/vector-icons/Ionicons';
import { router } from 'expo-router';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { clearPendingResearch, getPendingResearch } from './property-search-session';
export function ConfirmLocationScreen() {
  const pending = getPendingResearch();
  if (!pending) return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.title}>Doğrulanacak seçim bulunamadı</Text><Pressable accessibilityRole="button" onPress={() => router.replace('/(tabs)/map')} style={s.primary}><Text style={s.primaryText}>Aramaya dön</Text></Pressable></View></SafeAreaView>;
  const { draft, mode } = pending;
  const editSelection = () => { clearPendingResearch(); router.back(); };
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}>
    <Pressable accessibilityRole="button" accessibilityLabel="Seçimi düzenlemeye dön" onPress={editSelection} style={s.back}><Ionicons name="arrow-back" size={21} color="#0369A1" /><Text style={s.backText}>Seçimi düzenle</Text></Pressable>
    <Text style={s.eyebrow}>SON KONTROL</Text><Text style={s.title}>Konumu doğrula</Text><Text style={s.subtitle}>Devam etmeden önce seçimin doğru bölgeyi gösterdiğini kontrol et.</Text>
    <View style={s.card}><Text style={s.label}>{mode === 'property' ? 'EV / BİNA ARAŞTIRMASI' : 'BÖLGE ARAŞTIRMASI'}</Text><Text style={s.location}>{draft.neighborhood}, {draft.district}</Text><Text style={s.meta}>{draft.city}{draft.street ? ` · ${draft.street}` : ''}{draft.buildingNumber ? ` · No ${draft.buildingNumber}` : ''}</Text><Text style={s.warning}>{mode === 'property' ? 'Bu, senin seçtiğin konumdur; kesin bina kimliği veya resmî kayıt eşleşmesi değildir.' : 'Bu seçim bölge düzeyindedir ve bina hakkında kesin sonuç üretmez.'}</Text></View>
    <Pressable accessibilityRole="button" onPress={() => router.replace('/search/preparing')} style={s.primary}><Text style={s.primaryText}>Onayla ve devam et</Text></Pressable><Pressable accessibilityRole="button" onPress={editSelection} style={s.secondary}><Text style={s.secondaryText}>Seçimi düzenle</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F8FAFC' }, content: { padding: 20, paddingBottom: 40 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 }, back: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 8, alignSelf: 'flex-start' }, backText: { color: '#0369A1', fontWeight: '800' }, eyebrow: { color: '#0369A1', fontSize: 11, fontWeight: '800', letterSpacing: 1.2, marginTop: 14 }, title: { color: '#0F172A', fontSize: 27, fontWeight: '800', marginTop: 7, textAlign: 'center' }, subtitle: { color: '#475569', fontSize: 14, lineHeight: 21, marginTop: 6 }, card: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 20, padding: 18, marginTop: 24 }, label: { color: '#0369A1', fontSize: 11, fontWeight: '800' }, location: { color: '#0F172A', fontSize: 19, fontWeight: '800', marginTop: 8 }, meta: { color: '#475569', lineHeight: 20, marginTop: 5 }, warning: { color: '#78350F', backgroundColor: '#FFFBEB', borderRadius: 12, padding: 12, lineHeight: 19, marginTop: 16 }, primary: { minHeight: 52, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0369A1', borderRadius: 15, marginTop: 18, paddingHorizontal: 18 }, primaryText: { color: '#FFFFFF', fontWeight: '800' }, secondary: { minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: 8 }, secondaryText: { color: '#0369A1', fontWeight: '800' } });
