import Ionicons from '@expo/vector-icons/Ionicons';
import { useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import MapView, { Marker, type MapPressEvent } from 'react-native-maps';
import type { Coordinate } from './property-search.types';
type Target = { coordinate: Coordinate; delta: number } | null;
export function MapSelectionSurface({ enabled, coordinate, target, onSelect }: { enabled: boolean; coordinate: Coordinate | null; target: Target; onSelect: (value: Coordinate) => void }) {
  const mapRef = useRef<MapView>(null); const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading'); const [attempt, setAttempt] = useState(0);
  useEffect(() => { if (status !== 'loading') return; const timeout = setTimeout(() => setStatus('error'), 8000); return () => clearTimeout(timeout); }, [status, attempt]);
  useEffect(() => { if (status === 'ready' && target) mapRef.current?.animateToRegion({ latitude: target.coordinate.latitude, longitude: target.coordinate.longitude, latitudeDelta: target.delta, longitudeDelta: target.delta }, 450); }, [status, target]);
  if (status === 'error') return <View style={s.state}><Ionicons name="cloud-offline-outline" size={30} color="#64748B" /><Text style={s.title}>Harita yüklenemedi</Text><Text style={s.copy}>Seçimin korunuyor. Tekrar deneyebilir veya manuel konum girebilirsin.</Text><Pressable accessibilityRole="button" onPress={() => { setAttempt((value) => value + 1); setStatus('loading'); }} style={s.retry}><Text style={s.retryText}>Tekrar dene</Text></Pressable></View>;
  return <View style={[s.container, !enabled && s.disabled]}><MapView key={attempt} ref={mapRef} style={s.map} initialRegion={{ latitude: 39, longitude: 35, latitudeDelta: 12, longitudeDelta: 12 }} onMapReady={() => setStatus('ready')} onPress={(event: MapPressEvent) => onSelect(event.nativeEvent.coordinate)} scrollEnabled={enabled} zoomEnabled={enabled} pitchEnabled={false} accessibilityLabel="Konum seçme haritası">{coordinate && <Marker coordinate={coordinate} title="Seçilen nokta" description="Bina kaydı doğrulanmadı" />}</MapView>{status === 'loading' && <View accessibilityRole="progressbar" accessibilityLabel="Harita yükleniyor" style={s.loading}><Text style={s.copy}>Harita yükleniyor…</Text></View>}{!enabled && <View style={s.loading}><Text style={s.copy}>Haritayı kullanmak için önce mahalle seç.</Text></View>}</View>;
}
const s = StyleSheet.create({ container: { minHeight: 240, borderRadius: 20, overflow: 'hidden', borderWidth: 1, borderColor: '#7DD3FC', marginTop: 8 }, map: { minHeight: 240 }, disabled: { opacity: 0.62 }, loading: { ...StyleSheet.absoluteFill, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(224,242,254,0.92)', padding: 20 }, state: { minHeight: 220, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 20, padding: 22, marginTop: 8 }, title: { color: '#0F172A', fontSize: 16, fontWeight: '800', marginTop: 8 }, copy: { color: '#475569', textAlign: 'center', lineHeight: 19, marginTop: 6 }, retry: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 18, marginTop: 12 }, retryText: { color: '#0369A1', fontWeight: '800' } });
