import type { AddressCandidate, Coordinate } from './property-search.types';
const fixture = { İstanbul: { Kadıköy: ['Caferağa', 'Göztepe'], Avcılar: ['Ambarlı', 'Merkez'] }, Ankara: { Çankaya: ['Kızılay', 'Bahçelievler'] } } as const;
const addresses: AddressCandidate[] = [
  { id: 'caferaga-1', label: 'Caferağa · Moda Caddesi', matchLabel: 'Frontend geliştirme eşleşmesi', city: 'İstanbul', district: 'Kadıköy', neighborhood: 'Caferağa', street: 'Moda Caddesi', buildingNumber: '', coordinate: { latitude: 40.9819, longitude: 29.0267 }, selectionMethod: 'map' },
  { id: 'goztepe-1', label: 'Göztepe · Tütüncü Mehmet Efendi Caddesi', matchLabel: 'Frontend geliştirme eşleşmesi', city: 'İstanbul', district: 'Kadıköy', neighborhood: 'Göztepe', street: 'Tütüncü Mehmet Efendi Caddesi', buildingNumber: '', coordinate: { latitude: 40.9781, longitude: 29.0612 }, selectionMethod: 'map' },
  { id: 'ambarli-1', label: 'Ambarlı · Sahil Yolu', matchLabel: 'Frontend geliştirme eşleşmesi', city: 'İstanbul', district: 'Avcılar', neighborhood: 'Ambarlı', street: 'Sahil Yolu', buildingNumber: '', coordinate: { latitude: 40.9733, longitude: 28.7141 }, selectionMethod: 'map' },
  { id: 'kizilay-1', label: 'Kızılay · Atatürk Bulvarı', matchLabel: 'Frontend geliştirme eşleşmesi', city: 'Ankara', district: 'Çankaya', neighborhood: 'Kızılay', street: 'Atatürk Bulvarı', buildingNumber: '', coordinate: { latitude: 39.9208, longitude: 32.8541 }, selectionMethod: 'map' },
];
const centers: Record<string, Coordinate> = { İstanbul: { latitude: 41.0082, longitude: 28.9784 }, Ankara: { latitude: 39.9334, longitude: 32.8597 }, Kadıköy: { latitude: 40.9917, longitude: 29.0277 }, Avcılar: { latitude: 40.9799, longitude: 28.7218 }, Çankaya: { latitude: 39.9179, longitude: 32.8627 }, Caferağa: { latitude: 40.9819, longitude: 29.0267 }, Göztepe: { latitude: 40.9781, longitude: 29.0612 }, Ambarlı: { latitude: 40.9733, longitude: 28.7141 }, Merkez: { latitude: 40.98, longitude: 28.72 }, Kızılay: { latitude: 39.9208, longitude: 32.8541 }, Bahçelievler: { latitude: 39.925, longitude: 32.825 } };
export const cities = Object.keys(fixture);
export function getDistricts(city: string) { return city in fixture ? Object.keys(fixture[city as keyof typeof fixture]) : []; }
export function getNeighborhoods(city: string, district: string): string[] { const cityData = fixture[city as keyof typeof fixture]; return cityData && district in cityData ? [...cityData[district as keyof typeof cityData]] : []; }
export async function searchAddressFixture(query: string, city: string, district: string) { await new Promise((resolve) => setTimeout(resolve, 300)); if (typeof navigator !== 'undefined' && navigator.onLine === false) throw new Error('offline'); const needle = query.toLocaleLowerCase('tr'); return addresses.filter((item) => (!city || item.city === city) && (!district || item.district === district) && item.label.toLocaleLowerCase('tr').includes(needle)); }
export function getMapTarget(city: string, district: string, neighborhood: string, coordinate: Coordinate | null) { if (coordinate) return { coordinate, delta: 0.012 }; const key = neighborhood || district || city; return key && centers[key] ? { coordinate: centers[key], delta: neighborhood ? 0.025 : district ? 0.12 : 0.7 } : null; }
