import Ionicons from '@expo/vector-icons/Ionicons';
import { router } from 'expo-router';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { clearPendingResearch, getPendingResearch } from './property-search-session';
export function ReportPreparingScreen() {
  const pending = getPendingResearch();
  const finish = () => { clearPendingResearch(); router.replace('/(tabs)'); };
  const restart = () => { clearPendingResearch(); router.replace('/(tabs)/map'); };
  if (!pending) return <SafeAreaView style={s.safe}><View style={s.content}><Text style={s.title}>Hazırlanacak seçim bulunamadı</Text><Text style={s.copy}>Yeni bir ev veya bölge araştırması başlatabilirsin.</Text><Pressable accessibilityRole="button" onPress={restart} style={s.primary}><Text style={s.primaryText}>Aramaya dön</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><View style={s.content}>
    <View accessibilityElementsHidden importantForAccessibility="no-hide-descendants" style={s.icon}><Ionicons name="document-text-outline" size={42} color="#0369A1" /></View><Text style={s.eyebrow}>ARAŞTIRMA HAZIRLIĞI</Text><Text style={s.title}>{pending.mode === 'area' ? 'Bölge seçimin hazır' : 'Konum seçimin hazır'}</Text><Text style={s.copy}>Seçtiğin konumu onayladın. Kaynaklı rapor üretimi, veri servisleri bağlandığında bu adımdan başlayacak.</Text><View style={s.notice}><Text style={s.noticeTitle}>Henüz rapor sonucu üretilmedi</Text><Text style={s.noticeText}>Bu frontend adımı risk, skor, resmî adres eşleşmesi veya bina dayanımı sonucu vermez.</Text></View><Pressable accessibilityRole="button" onPress={finish} style={s.primary}><Text style={s.primaryText}>Ana sayfaya dön</Text></Pressable><Pressable accessibilityRole="button" onPress={restart} style={s.secondary}><Text style={s.secondaryText}>Yeni araştırma yap</Text></Pressable>
  </View></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F8FAFC' }, content: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 }, icon: { width: 84, height: 84, borderRadius: 42, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E0F2FE' }, eyebrow: { color: '#0369A1', fontSize: 11, fontWeight: '800', letterSpacing: 1.2, marginTop: 22 }, title: { color: '#0F172A', fontSize: 27, fontWeight: '800', marginTop: 7, textAlign: 'center' }, copy: { color: '#475569', fontSize: 14, lineHeight: 22, textAlign: 'center', marginTop: 8 }, notice: { width: '100%', backgroundColor: '#FFFBEB', borderColor: '#FDE68A', borderWidth: 1, borderRadius: 16, padding: 15, marginTop: 22 }, noticeTitle: { color: '#78350F', fontWeight: '800' }, noticeText: { color: '#78350F', lineHeight: 19, marginTop: 5 }, primary: { width: '100%', minHeight: 52, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0369A1', borderRadius: 15, marginTop: 22 }, primaryText: { color: '#FFFFFF', fontWeight: '800' }, secondary: { minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: 8 }, secondaryText: { color: '#0369A1', fontWeight: '800' } });
