import Ionicons from '@expo/vector-icons/Ionicons';
import { useLocalSearchParams, router } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';

type Mode = 'property' | 'area';

export default function SearchScreen() {
  const params = useLocalSearchParams<{ mode?: string }>();
  const [mode, setMode] = useState<Mode>(params.mode === 'area' ? 'area' : 'property');
  const [query, setQuery] = useState('');
  return <SafeAreaView style={s.safe}><View style={s.content}><Text style={s.eyebrow}>ARAMA</Text><Text style={s.title}>{mode === 'property' ? 'Bir evi incele' : 'Bölgeyi keşfet'}</Text><Text style={s.subtitle}>{mode === 'property' ? 'Adres gir veya haritadan binayı seç.' : 'Mahalle ya da ilçeyi yaşam ve konum açısından incele.'}</Text><View accessibilityRole="tablist" style={s.tabs}><ModeButton label="Ev / bina" selected={mode === 'property'} onPress={() => setMode('property')} /><ModeButton label="Bölge" selected={mode === 'area'} onPress={() => setMode('area')} /></View><Text style={s.label}>{mode === 'property' ? 'Adres veya bina' : 'Mahalle veya ilçe'}</Text><View style={s.inputRow}><Ionicons name="search" size={20} color="#475569" /><TextInput autoFocus accessibilityLabel={mode === 'property' ? 'Adres veya bina ara' : 'Mahalle veya ilçe ara'} value={query} onChangeText={setQuery} placeholder={mode === 'property' ? 'Adres veya bina ara' : 'Mahalle veya ilçe ara'} placeholderTextColor="#64748B" style={s.input} /></View><View style={s.notice}><Ionicons name="information-circle-outline" size={20} color="#0369A1" /><Text style={s.noticeText}>Konum seçimi rapor hazırlanmadan önce sana doğrulatılır.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Ana sayfaya dön" onPress={() => router.push('/(tabs)')} style={s.back}><Text style={s.backText}>Ana sayfaya dön</Text></Pressable></View></SafeAreaView>;
}
function ModeButton({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="tab" accessibilityState={{ selected }} onPress={onPress} style={[s.mode, selected && s.modeSelected]}><Text style={[s.modeText, selected && s.modeTextSelected]}>{selected ? '✓ ' : ''}{label}</Text></Pressable>; }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F8FAFC' }, content: { padding: 20, paddingBottom: 100 }, eyebrow: { color: '#0369A1', fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, title: { color: '#0F172A', fontSize: 27, fontWeight: '800', marginTop: 7 }, subtitle: { color: '#475569', fontSize: 14, lineHeight: 21, marginTop: 5 }, tabs: { flexDirection: 'row', gap: 8, marginTop: 24 }, mode: { flex: 1, minHeight: 46, alignItems: 'center', justifyContent: 'center', borderRadius: 14, borderWidth: 1, borderColor: '#CBD5E1', backgroundColor: '#FFFFFF' }, modeSelected: { borderColor: '#0369A1', backgroundColor: '#E0F2FE' }, modeText: { color: '#475569', fontWeight: '700' }, modeTextSelected: { color: '#075985' }, label: { color: '#0F172A', fontSize: 12, fontWeight: '700', marginTop: 24, marginBottom: 8 }, inputRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#94A3B8', borderRadius: 16, paddingHorizontal: 15, backgroundColor: '#FFFFFF' }, input: { flex: 1, minHeight: 56, color: '#0F172A', fontSize: 15 }, notice: { flexDirection: 'row', gap: 9, backgroundColor: '#F0F9FF', borderRadius: 14, padding: 14, marginTop: 16 }, noticeText: { flex: 1, color: '#075985', fontSize: 12, lineHeight: 18 }, back: { minHeight: 44, justifyContent: 'center', alignSelf: 'center', paddingHorizontal: 16, marginTop: 18 }, backText: { color: '#0369A1', fontWeight: '700' } });
