import Ionicons from '@expo/vector-icons/Ionicons';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { homeTheme as c } from '../home-theme';
import type { RecentResearchState } from '../home.types';

type Props = { state: RecentResearchState; onPropertySearch: () => void; onAreaSearch: () => void; onRetry: () => void; onResearchPress: (target: string) => void };

export function RecentResearchSection(p: Props) {
  return <View style={s.section}><Text style={s.heading}>Son araştırmalar</Text><Text style={s.subheading}>Kaldığın yerden devam et</Text>{p.state.status === 'loading' && <LoadingState />}{p.state.status === 'error' && <ErrorState onRetry={p.onRetry} />}{p.state.status === 'empty' && <EmptyState onPropertySearch={p.onPropertySearch} onAreaSearch={p.onAreaSearch} />}{p.state.status === 'populated' && <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{p.state.items.slice(0, 3).map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`${item.locationLabel}, ${item.contextLabel}`} onPress={() => p.onResearchPress(item.target)} style={({ pressed }) => [s.recentCard, pressed && s.pressed]}><Text style={s.context}>{item.contextLabel}</Text><Text style={s.location}>{item.locationLabel}</Text><Text style={s.time}>{item.lastViewedLabel}</Text>{item.statusLabel && <Text style={s.status}>{item.statusLabel}</Text>}</Pressable>)}</ScrollView>}</View>;
}

function LoadingState() {
  return <View accessibilityLabel="Son araştırmalar yükleniyor" accessibilityRole="progressbar" style={s.row}>{[0, 1, 2].map((key) => <View key={key} style={s.skeleton}><View style={s.skeletonLine} /><View style={s.skeletonShort} /></View>)}</View>;
}

function ErrorState({ onRetry }: { onRetry: () => void }) {
  return <View style={s.stateCard}><Ionicons name="cloud-offline-outline" size={32} color={c.muted} /><Text style={s.stateTitle}>Son araştırmalar yüklenemedi.</Text><Text style={s.stateText}>Arama ve keşif seçeneklerini kullanmaya devam edebilirsin.</Text><Pressable accessibilityRole="button" accessibilityLabel="Son araştırmaları tekrar yükle" onPress={onRetry} style={s.retry}><Text style={s.retryText}>Tekrar dene</Text></Pressable></View>;
}

function EmptyState({ onPropertySearch, onAreaSearch }: { onPropertySearch: () => void; onAreaSearch: () => void }) {
  return <View style={s.stateCard}><View accessibilityElementsHidden importantForAccessibility="no-hide-descendants" style={s.art}><View style={s.halo} /><Ionicons name="home" size={42} color={c.accent} /><Ionicons name="location" size={24} color={c.accentDark} /></View><Text style={s.stateTitle}>İlk ev araştırmana başlayalım</Text><Text style={s.stateText}>Bir adres ara veya haritadan bir bina seç; erişilebilen bilgileri tek bir raporda toplayalım.</Text><Pressable accessibilityRole="button" accessibilityLabel="Ev konumu ara" onPress={onPropertySearch} style={s.primary}><Text style={s.primaryText}>Ev konumu ara</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Bir bölgeyi keşfet" hitSlop={8} onPress={onAreaSearch} style={s.secondary}><Text style={s.secondaryText}>Bir bölgeyi keşfet →</Text></Pressable></View>;
}

const s = StyleSheet.create({ section: { marginTop: 28 }, heading: { color: c.text, fontSize: 18, fontWeight: '800' }, subheading: { color: c.muted, fontSize: 12, marginTop: 3, marginBottom: 12 }, row: { flexDirection: 'row', gap: 12 }, recentCard: { width: 238, minHeight: 150, backgroundColor: c.surface, borderColor: c.border, borderWidth: 1, borderRadius: 18, padding: 16 }, context: { color: c.accentDark, fontSize: 11, fontWeight: '700' }, location: { color: c.text, fontSize: 16, fontWeight: '800', marginTop: 8 }, time: { color: c.muted, fontSize: 12, marginTop: 6 }, status: { color: c.text, fontSize: 11, fontWeight: '700', marginTop: 14 }, skeleton: { width: 210, height: 130, borderRadius: 18, backgroundColor: '#EEF2F6', padding: 18 }, skeletonLine: { height: 15, width: '80%', borderRadius: 8, backgroundColor: '#DCE3EA', marginTop: 18 }, skeletonShort: { height: 12, width: '48%', borderRadius: 8, backgroundColor: '#DCE3EA', marginTop: 12 }, stateCard: { alignItems: 'center', backgroundColor: c.surface, borderColor: c.border, borderWidth: 1, borderRadius: 24, padding: 22 }, art: { width: 150, height: 92, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center', marginBottom: 10 }, halo: { position: 'absolute', width: 92, height: 92, borderRadius: 46, backgroundColor: c.accentLight }, stateTitle: { color: c.text, fontSize: 18, fontWeight: '800', textAlign: 'center', marginTop: 8 }, stateText: { color: c.muted, fontSize: 13, lineHeight: 20, textAlign: 'center', marginTop: 7, marginBottom: 16 }, primary: { width: '100%', minHeight: 50, alignItems: 'center', justifyContent: 'center', backgroundColor: c.accent, borderRadius: 15 }, primaryText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' }, secondary: { minHeight: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 }, secondaryText: { color: c.accentDark, fontSize: 13, fontWeight: '700' }, retry: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 18, borderRadius: 12, borderColor: c.border, borderWidth: 1 }, retryText: { color: c.accentDark, fontWeight: '800' }, pressed: { opacity: 0.72 } });
